
name : Alpha

on :
  pull_request :
    branches:
      - beta

env:
  CARGO_TERM_COLOR: always

jobs :

  # check:
  #   runs-on : ubuntu-latest
  #   outputs:
  #     shouldRun: ${{ steps.run.outputs.shouldRun }}
  #   steps :
  #     - name: List commits on the pull request
  #       run: |
  #         response=$(curl --request GET \
  #         --url 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits' \
  #         --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
  #         --header 'Accept: application/vnd.github.v3+json' \
  #         --header 'Content-Type: application/json')
  #         echo $response > response.json
  #     - name: Get latest commit
  #       id: message
  #       run: |
  #         length=$(jq 'length' response.json)
  #         index=$(($length - 1))
  #         latest_commit=$(jq --argjson index $index '.[$index]' response.json)
  #         latest_commit_message=$(echo "$latest_commit" | jq -r '.commit.message')
  #         echo "::set-output name=message::$latest_commit_message"
  #     - name : Exit with fail
  #       id: run
  #       if: "!contains( steps.message.outputs.message, '[build]' ) && !startsWith( steps.message.outputs.message, 'Merge ' )"
  #       run: echo "::set-output name=shouldRun::false"
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v1.1
        with:
          target: beta
          exclude: Wandalen:alpha
      - name: Error message
        if: ${{ failure() }}
        run : echo -e 'To save the application stability the repository uses a system to forward changes from an unstable branch to a stable.\nThe unstable branch is `alpha`. All user pull requests should be opened to this branch.\nThe staging branch is `beta`. Changes to this branch are forwarded by a pull request from branch `alpha` automatically.\nThe stable branch is `master`. Changes to this branch are forwarded by a pull request from branch `beta` automatically. Forwarded changes merge manually after review.\n\nThe base branch of this PR has been automatically changed to `alpha` taking into account the described system `alpha -> beta -> master`.\nPlease, check that there are no merge conflicts.'


  desktop_fast:
    needs: check
    # if: ${{ needs.check.outputs.shouldRun != 'false' }}
    uses: Wandalen/game_chess/.github/workflows/DesktopCommon.yml@main
    with:
      artifacts: 'false'
      build: 'fast'
      toolchain: 'stable'
  desktop:
    needs: check
    # if: ${{ needs.check.outputs.shouldRun != 'false' }}
    uses: Wandalen/game_chess/.github/workflows/DesktopCommon.yml@main
    with:
      artifacts: 'false'
      build: 'slow'
      toolchain: 'nightly'

  # web_fast:
  #   needs: check
  #   # if: ${{ needs.check.outputs.shouldRun != 'false' }}
  #   uses: Wandalen/game_chess/.github/workflows/WebCommon.yml@main
  #   with:
  #     artifacts: 'false'
  #     build: 'fast'
  #     toolchain: 'stable'
  # web:
  #   needs: check
  #   # if: ${{ needs.check.outputs.shouldRun != 'false' }}
  #   uses: Wandalen/game_chess/.github/workflows/WebCommon.yml@main
  #   with:
  #     artifacts: 'true'
  #     build: 'slow'
  #     toolchain: 'nightly'

  # forward :
  #   # needs: [ desktop, web ]
  #   needs: [ desktop ]
  #   runs-on : ubuntu-latest
  #   steps :
  #     - uses: actions/checkout@v2
  #     - uses : everlytic/branch-merge@1.1.2
  #       with :
  #         github_token : ${{ secrets.PRIVATE_GITHUB_TOKEN }}
  #         source_ref : alpha
  #         target_branch : beta
  #         commit_message_template : 'Merge {source_ref} into {target_branch} [Automated]'

