
name: ForwardFromAlpha

on:
  push:
    branches: [ alpha ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Open Pr
        uses: vsoch/pull-request-action@1.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: beta
          PULL_REQUEST_TITLE: 'READY : Forward from alpha to beta'
          PASS_IF_EXISTS: true

