
name : MainPrApprove

on:
  pull_request_target:
    types: [ opened, reopened, edited ]

jobs :

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        with:
          target: main
          exclude: Wandalen:beta
          change-to: alpha
          comment: |
            The base branch of this PR has been automatically changed to `alpha`, please check that there are no merge conflicts.
